name: Codebase Sphinx Documentation

on:
  push:
    branches: [ codebase-docs ]
    # change to on merge when complete
jobs:
  build_docs_job:
    name: Code Reference Generator
    runs-on: ubuntu-latest
    env: 
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
              python-version: 3.9

      - name: Install dependencies
        run: |
              python -m pip install -U sphinx
              python -m pip install furo
              python -m pip install django
              python -m pip install os
              python -m pip install sys
              python -m pip install mock

      - name: Make the Codebase Reference sphinx docs
        run: |
              cd docs/codebase_docs/
              sphinx-build -b html source ..

      - name: Init new codebase docs repo
        run: |
              cd docs/
              git init
              touch .nojekyll
              git add -A
              git config --local user.email "alex_coldea@yahoo.com"
              git config --local user.name "alexcoldea"


      - name: Push to destination branch
        uses: ad-m/github-push-action@0.5.0
        with: 
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: gh_pages
            force: true
            directory: .docs/

